name: pdf-deployment

on:
  push:
    tags:
      - "rev*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build PDF
        run: |
          docker-compose build
          echo "Update mpm db"
          docker-compose run tex mpm --update-db
          docker-compose run tex pdflatex main.tex

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set github SHA short
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.24

      - name: Terraform Init
        run: |
          cd ./tf
          terraform init

      - name: Terraform Plan
        env:
          TF_VAR_dest_bucket_name: ${{ secrets.DEST_BUCKET_NAME }}
          TF_VAR_github_sha: ${{ env.GITHUB_SHA_SHORT }}
        run: |
          cd ./tf
          terraform plan -out=plan

      - name: Terraform Apply
        env:
          TF_VAR_dest_bucket_name: ${{ secrets.DEST_BUCKET_NAME }}
          TF_VAR_github_sha: ${{ env.GITHUB_SHA_SHORT }}
        run: |
          cd ./tf
          terraform apply plan

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Current release: https://${{ secrets.RELEASE_URL_PREFIX }}/kandi-${{ env.GITHUB_SHA_SHORT }}.pdf
          draft: false
          prerelease: false
